export type Book = {
  bookName: string;
  articles: Lesson[];
};

export type Lesson = {
  index: number;
  title: string;
  asterisk?: boolean;
  sections?: string[];
} | {  activity: string;
  topic: string;};

const renjiaoshe: Book[] = [
  {
    bookName: '一年级上册',
    articles: [
{activity: '拼音', topic: 'a o e'},
{activity: '拼音', topic: 'i u ü'},
{activity: '拼音', topic: 'b p m f'},
{activity: '拼音', topic: 'd t n l'},
{activity: '拼音', topic: 'g k h'},
{activity: '拼音', topic: 'j q x'},
{activity: '拼音', topic: 'z c s'},
{activity: '拼音', topic: 'zh ch sh r'},
{activity: '拼音', topic: 'y w'},
{activity: '拼音', topic: 'ai ei ui'},
{activity: '拼音', topic: 'ao ou iu'},
{activity: '拼音', topic: 'ie üe er'},
{activity: '拼音', topic: 'an en in un ün'},
{activity: '拼音', topic: 'ang eng ing ong'},
      { index: 1, title: '一去二三里' },
      { index: 2, title: '口耳目' },
      { index: 3, title: '在家里' },
      { index: 4, title: '操场上' },
      { index: 1, title: '画' },
      { index: 2, title: '四季' },
      { index: 3, title: '小小竹排画中游' },
      { index: 4, title: '哪座房子最漂亮' },
      { index: 5, title: '爷爷和小树' },
      { index: 6, title: '静夜思' },
      { index: 7, title: '小小的船' },
      { index: 8, title: '阳光' },
      { index: 9, title: '影子' },
      { index: 10, title: '比尾巴' },
      { index: 1, title: '比一比' },
      { index: 2, title: '自选商场' },
      { index: 3, title: '菜园里' },
      { index: 4, title: '日月明' },
      { index: 11, title: '我多想去看看' },
      { index: 12, title: '雨点儿' },
      { index: 13, title: '平平搭积木' },
      { index: 14, title: '自己去吧' },
      { index: 15, title: '一次比一次有进步' },
      { index: 16, title: '小松鼠找花生' },
      { index: 17, title: '雪地里的小画家' },
      { index: 18, title: '借生日' },
      { index: 19, title: '雪孩子' },
      { index: 20, title: '小熊住山洞' },
    ],
  },
  {
    bookName: '一年级下册',
    articles: [
      { index: 1, title: '柳树醒了' },
      { index: 2, title: '春雨的色彩' },
      { index: 3, title: '邓小平爷爷植树' },
      { index: 4, title: '古诗两首', sections: ['春晓', '村居'] },
      { index: 5, title: '看电视' },
      { index: 6, title: '胖乎乎的小手' },
      { index: 7, title: '棉鞋里的阳光' },
      { index: 8, title: '月亮的心愿' },
      { index: 9, title: '两只鸟蛋' },
      { index: 10, title: '松鼠和松果' },
      { index: 11, title: '美丽的小路' },
      { index: 12, title: '失物招领' },
      { index: 13, title: '古诗两首', sections: ['所见', '小池'] },
      { index: 14, title: '荷叶圆圆' },
      { index: 15, title: '夏夜多美' },
      { index: 16, title: '要下雨了' },
      { index: 17, title: '小壁虎借尾巴' },
      { index: 18, title: '四个太阳' },
      { index: 19, title: '乌鸦喝水' },
      { index: 20, title: '司马光' },
      { index: 21, title: '称象' },
      { index: 22, title: '吃水不忘挖井人' },
      { index: 23, title: '王二小' },
      { index: 24, title: '画家乡' },
      { index: 25, title: '快乐的节日' },
      { index: 26, title: '小白兔和小灰兔' },
      { index: 27, title: '两只小狮子' },
      { index: 28, title: '小伙伴' },
      { index: 29, title: '手捧花盆的孩子' },
      { index: 30, title: '棉花姑娘' },
      { index: 31, title: '地球爷爷的手' },
      { index: 32, title: '兰兰过桥' },
      { index: 33, title: '火车的故事' },
      { index: 34, title: '小蝌蚪找妈妈' },
    ],
  },
  {
    bookName: '二年级上册',
    articles: [
      { index: 1, title: '秋天的图画' },
      { index: 2, title: '黄山奇石' },
      { index: 3, title: '植物妈妈有办法' },
      { index: 4, title: '古诗两首', sections: ['赠刘景文', '山行'] },
      { index: 5, title: '一株紫丁香' },
      { index: 6, title: '我选我' },
      { index: 7, title: '一分钟' },
      { index: 8, title: '难忘的一天' },
      { index: 9, title: '欢庆' },
      { index: 10, title: '北京' },
      { index: 11, title: '我们成功了' },
      { index: 12, title: '看雪' },
      { index: 13, title: '坐井观天' },
      { index: 14, title: '我要的是葫芦' },
      { index: 15, title: '小柳树和小枣树' },
      { index: 16, title: '风娃娃' },
      { index: 17, title: '酸的和甜的' },
      { index: 18, title: '称赞' },
      { index: 19, title: '蓝色的树叶' },
      { index: 20, title: '纸船和风筝' },
      { index: 21, title: '从现在开始' },
      { index: 22, title: '窗前的气球' },
      { index: 23, title: '假如' },
      { index: 24, title: '日记两则' },
      { index: 25, title: '古诗两首', sections: ['回乡偶书', '赠汪伦'] },
      { index: 26, title: '“红领巾”真好' },
      { index: 27, title: '清澈的湖水' },
      { index: 28, title: '浅水洼里的小鱼' },
      { index: 29, title: '父亲和鸟' },
      { index: 30, title: '我是什么' },
      { index: 31, title: '回声' },
      { index: 32, title: '太空生活趣事多' },
      { index: 33, title: '活化石' },
      { index: 34, title: '农业的变化真大' },
    ],
  },
  {
    bookName: '二年级下册',
    articles: [
      { index: 1, title: '找春天' },
      {
        index: 2,
        title: '古诗两首',
        sections: ['《草》白居易', '宿新市徐公店'],
      },
      { index: 3, title: '芛芽儿' },
      { index: 4, title: '小鹿的玫瑰花' },
      { index: 5, title: '泉水' },
      { index: 6, title: '雷锋叔叔，你在哪里' },
      { index: 7, title: '我不是最弱小的' },
      { index: 8, title: '卡罗尔和她的小猫' },
      { index: 9, title: '日月潭' },
      { index: 10, title: '葡萄沟' },
      { index: 11, title: '难忘的泼水节' },
      { index: 12, title: '北京亮起来了' },
      { index: 13, title: '动手做做看' },
      { index: 14, title: '邮票齿孔的故事' },
      { index: 15, title: '画风' },
      { index: 16, title: '充气雨衣' },
      { index: 17, title: '古诗两首', sections: ['望庐山瀑布', '绝句'] },
      { index: 18, title: '雷雨' },
      { index: 19, title: '最大的“书”' },
      { index: 20, title: '要是你在野外迷了路' },
      { index: 21, title: '画家和牧童' },
      { index: 22, title: '我为你骄傲' },
      { index: 23, title: '三个儿子' },
      { index: 24, title: '玩具柜台前的孩子' },
      { index: 25, title: '玲玲的画' },
      { index: 26, title: '蜜蜂引路' },
      { index: 27, title: '寓言两则', sections: ['揠苗助长', '守株待兔'] },
      { index: 28, title: '丑小鸭' },
      { index: 29, title: '数星星的孩子' },
      { index: 30, title: '爱迪生救妈妈' },
      { index: 31, title: '恐龙的灭绝' },
      { index: 32, title: '阿德的梦' },
    ],
  },
  {
    bookName: '三年级上册',
    articles: [
      { index: 1, title: '我们的民族小学' },
      { index: 2, title: '金色的草地' },
      { index: 3, title: '爬天都峰' },
      { index: 4, title: '槐乡的孩子' },
      { index: 5, title: '灰雀' },
      { index: 6, title: '小摄影师' },
      { index: 7, title: '奇怪的大石头' },
      { index: 8, title: '我不能失信', asterisk: true },
      {
        index: 9,
        title: '古诗两首',
        sections: ['夜书所见', '九月九日忆山东兄弟'],
      },
      { index: 10, title: '风筝' },
      { index: 11, title: '秋天的雨' },
      { index: 12, title: '听听，秋的声音', asterisk: true },
      { index: 13, title: '花钟' },
      { index: 14, title: '蜜蜂' },
      { index: 15, title: '玩出了名堂' },
      { index: 16, title: '找骆驼', asterisk: true },
      { index: 17, title: '孔子拜师' },
      { index: 18, title: '盘古开天地' },
      { index: 19, title: '赵州桥' },
      { index: 20, title: '一幅名扬中外的画', asterisk: true },
      {
        index: 21,
        title: '古诗两首',
        sections: ['望天门山', '饮湖上初晴后雨'],
      },
      { index: 22, title: '富饶的西沙群岛' },
      { index: 23, title: '美丽的小兴安岭' },
      { index: 24, title: '香港，璀璨的明珠', asterisk: true },
      { index: 25, title: '矛和盾的集合' },
      { index: 26, title: '科利亚的木匣' },
      { index: 27, title: '陶罐和铁罐' },
      { index: 28, title: '狮子和鹿' },
      { index: 29, title: '掌声' },
      { index: 30, title: '一次成功的实验' },
      { index: 31, title: '给予树' },
      { index: 32, title: '好汉查理', asterisk: true },
    ],
  },
  {
    bookName: '三年级下册',
    articles: [
      { index: 1, title: '燕子' },
      { index: 2, title: '古诗两首', sections: ['咏柳', '春日'] },
      { index: 3, title: '荷花' },
      { index: 4, title: '珍珠泉', asterisk: true },
      { index: 5, title: '翠鸟' },
      { index: 6, title: '燕子专列' },
      { index: 7, title: '一个小村庄的故事' },
      { index: 8, title: '路旁的橡树', asterisk: true },
      { index: 9, title: '寓言两则', sections: ['亡羊补牢', '南辕北辙'] },
      { index: 10, title: '惊弓之鸟' },
      { index: 11, title: '画杨桃' },
      { index: 12, title: '想别人没想到的', asterisk: true },
      { index: 13, title: '和时间赛跑' },
      { index: 14, title: '检阅' },
      { index: 15, title: '争吵' },
      { index: 16, title: '绝招', asterisk: true },
      { index: 17, title: '可贵的沉默' },
      { index: 18, title: '她是我的朋友' },
      { index: 19, title: '七颗钻石' },
      { index: 20, title: '妈妈的账单' },
      { index: 21, title: '太阳' },
      { index: 22, title: '月球之谜' },
      { index: 23, title: '我家跨上了“信息高速路”' },
      { index: 24, title: '果园机器人', asterisk: true },
      { index: 25, title: '太阳是大家的' },
      { index: 26, title: '一面五星红旗' },
      { index: 27, title: '卖木雕的少年' },
      { index: 28, title: '中国国际救援队，真棒!', asterisk: true },
      { index: 29, title: '古诗两首', sections: ['乞巧', '嫦娥（李商隐）'] },
      { index: 30, title: '西门豹' },
      { index: 31, title: '女娲补天' },
      { index: 32, title: '夸父追日', asterisk: true },
    ],
  },
  {
    bookName: '四年级上册',
    articles: [
      { index: 1, title: '观潮' },
      { index: 2, title: '雅鲁藏布大峡谷', asterisk: true },
      { index: 3, title: '鸟的天堂' },
      { index: 4, title: '火烧云', asterisk: true },
      { index: 5, title: '古诗两首', sections: ['题西林壁', '游山西村'] },
      { index: 6, title: '爬山虎的脚' },
      { index: 7, title: '蟋蟀的住宅' },
      { index: 8, title: '世界地图引出的发现', asterisk: true },
      { index: 9, title: '巨人的花园' },
      { index: 10, title: '幸福是什么', asterisk: true },
      { index: 11, title: '去年的树' },
      { index: 12, title: '小木偶的故事', asterisk: true },
      { index: 13, title: '白鹅' },
      { index: 14, title: '白公鹅', asterisk: true },
      { index: 15, title: '猫' },
      { index: 16, title: '母鸡', asterisk: true },
      { index: 17, title: '长城' },
      { index: 18, title: '颐和园' },
      { index: 19, title: '秦兵马俑', asterisk: true },
      {
        index: 20,
        title: '古诗两首',
        sections: ['黄鹤楼送孟浩然之广陵', '送元二使安西'],
      },
      { index: 21, title: '搭石' },
      { index: 22, title: '跨越海峡的生命桥' },
      { index: 23, title: '卡罗纳', asterisk: true },
      { index: 24, title: '给予是快乐的', asterisk: true },
      { index: 25, title: '为中华之崛起而读书' },
      { index: 26, title: '那片绿绿的爬山虎' },
      { index: 27, title: '乌塔', asterisk: true },
      { index: 28, title: '尺有所短 寸有所长', asterisk: true },
      { index: 29, title: '呼风唤雨的世纪' },
      { index: 30, title: '电脑住宅', asterisk: true },
      { index: 31, title: '飞向蓝天的恐龙' },
      { index: 32, title: '飞船上的特殊乘客', asterisk: true },
    ],
  },
  {
    bookName: '四年级下册',
    articles: [
      {
        index: 1,
        title: '古诗词三首',
        sections: ['独坐敬亭山', '望洞庭', '忆江南'],
      },
      { index: 2, title: '桂林山水' },
      { index: 3, title: '记金华的双龙洞' },
      { index: 4, title: '七月的天山' },
      { index: 5, title: '中彩那天' },
      { index: 6, title: '万年牢' },
      { index: 7, title: '尊严' },
      { index: 8, title: '将心比心' },
      { index: 9, title: '自然之道' },
      { index: 10, title: '黄河是怎样变化的' },
      { index: 11, title: '蝙蝠和雷达' },
      { index: 12, title: '大自然的启示' },
      { index: 13, title: '夜莺的歌声' },
      { index: 14, title: '小英雄雨来' },
      { index: 15, title: '一个中国孩子的呼声' },
      { index: 16, title: '和我们一样享受春天' },
      { index: 17, title: '触摸春天' },
      { index: 18, title: '永生的眼睛' },
      { index: 19, title: '生命 生命' },
      { index: 20, title: '花的勇气' },
      { index: 21, title: '乡下人家' },
      { index: 22, title: '牧场之国' },
      {
        index: 23,
        title: '古诗词三首',
        sections: ['乡村四月', '四时田园杂兴', '渔歌子'],
      },
      { index: 24, title: '麦哨' },
      { index: 25, title: '两个铁球同时着地' },
      { index: 26, title: '全神贯注' },
      { index: 27, title: '鱼游到了纸上' },
      { index: 28, title: '父亲的菜园' },
      { index: 29, title: '寓言两则', sections: ['纪昌学射', '扁鹊治病'] },
      { index: 30, title: '文成公主进藏' },
      { index: 31, title: '普罗米修斯' },
      { index: 32, title: '渔夫的故事' },
    ],
  },
  {
    bookName: '五年级上册',
    articles: [
      { index: 1, title: '窃读记' },
      { index: 2, title: '小苗与大树的对话' },
      { index: 3, title: '走遍天下书为侣' },
      { index: 4, title: '我的“长生果”' },
      {
        index: 5,
        title: '古诗词三首',
        sections: ['泊船瓜洲', '秋思', '长相思'],
      },
      { index: 6, title: '梅花魂' },
      { index: 7, title: '桂花雨' },
      { index: 8, title: '小桥流水人家' },
      { index: 9, title: '鲸' },
      { index: 10, title: '松鼠' },
      { index: 11, title: '新型玻璃' },
      { index: 12, title: '假如没有灰尘' },
      { index: 13, title: '钓鱼的启示' },
      { index: 14, title: '通往广场的路不止一条' },
      { index: 15, title: '落花生' },
      { index: 16, title: '珍珠鸟' },
      { index: 17, title: '地震中的父与子' },
      { index: 18, title: '慈母情深' },
      { index: 19, title: '“精彩极了”和“糟糕透了”' },
      { index: 20, title: '学会看病' },
      { index: 21, title: '圆明园的毁灭' },
      { index: 22, title: '狼牙山五壮士' },
      { index: 23, title: '难忘的一课' },
      { index: 24, title: '最后一分钟' },
      { index: 25, title: '七律·长征' },
      { index: 26, title: '开国大典' },
      { index: 27, title: '青山处处埋忠骨' },
      { index: 28, title: '毛主席在花山' },
    ],
  },
  {
    bookName: '五年级下册',
    articles: [
      { index: 1, title: '草原' },
      { index: 2, title: '丝绸之路', asterisk: true },
      { index: 3, title: '白杨' },
      { index: 4, title: '把铁路修到拉萨去', asterisk: true },
      {
        index: 5,
        title: '古诗词三首',
        sections: ['牧童', '舟过安仁', '清平乐·村居'],
      },
      { index: 6, title: '冬阳·童年·骆驼队' },
      { index: 7, title: '祖父的园子', asterisk: true },
      { index: 8, title: '童年的发现' },
      { index: 9, title: '儿童诗两首', asterisk: true },
      { index: 10, title: '杨氏之子' },
      { index: 11, title: '晏子使楚' },
      { index: 12, title: '半截蜡烛', asterisk: true },
      { index: 13, title: '打电话', asterisk: true },
      { index: 14, title: '再见了，亲人' },
      { index: 15, title: '金色的鱼钩', asterisk: true },
      { index: 16, title: '桥' },
      { index: 17, title: '梦想的力量', asterisk: true },
      { index: 18, title: '将相和' },
      { index: 19, title: '草船借箭' },
      { index: 20, title: '景阳冈', asterisk: true },
      { index: 21, title: '猴王出世', asterisk: true },
      { index: 22, title: '人物描写一组' },
      { index: 23, title: '刷子李', asterisk: true },
      { index: 24, title: '金钱的魔力', asterisk: true },
      { index: 25, title: '自己的花是让别人看的' },
      { index: 26, title: '威尼斯的小艇' },
      { index: 27, title: '与象共舞', asterisk: true },
      { index: 28, title: '彩色的非洲', asterisk: true },
    ],
  },
  {
    bookName: '六年级上册',
    articles: [
      { index: 1, title: '山中访友' },
      { index: 2, title: '山雨', asterisk: true },
      { index: 3, title: '草虫的村落' },
      { index: 4, title: '索溪峪的“野”', asterisk: true },
      { index: 5, title: '詹天佑' },
      { index: 6, title: '怀念母亲' },
      { index: 7, title: '彩色的翅膀', asterisk: true },
      { index: 8, title: '中华少年', asterisk: true },
      { index: 9, title: '穷人' },
      { index: 10, title: '别饿坏了那匹马' },
      { index: 11, title: '唯一的听众' },
      { index: 12, title: '用心灵去倾听', asterisk: true },
      { index: 13, title: '只有一个地球' },
      { index: 14, title: '大瀑布的葬礼', asterisk: true },
      { index: 15, title: '这片土地是神圣的' },
      { index: 16, title: '青山不老', asterisk: true },
      { index: 17, title: '少年闰土' },
      { index: 18, title: '我的伯父鲁迅先生' },
      { index: 19, title: '一面', asterisk: true },
      { index: 20, title: '有的人', asterisk: true },
      { index: 21, title: '老人与海鸥' },
      { index: 22, title: '跑进家来的松鼠', asterisk: true },
      { index: 23, title: '最后一头战象' },
      { index: 24, title: '金色的脚印', asterisk: true },
      { index: 25, title: '伯牙绝弦' },
      { index: 26, title: '月光曲' },
      { index: 27, title: '蒙娜丽莎之约', asterisk: true },
      { index: 28, title: '我的舞台', asterisk: true },
    ],
  },
  {
    bookName: '六年级下册',
    articles: [
      { index: 1, title: '文言文两则', sections: ['学弈', '两小儿辩日'] },
      { index: 2, title: '匆匆' },
      { index: 3, title: '桃花心木' },
      { index: 4, title: '顶碗少年', asterisk: true },
      { index: 5, title: '手指', asterisk: true },
      { index: 6, title: '北京的春节' },
      { index: 7, title: '藏戏', asterisk: true },
      { index: 8, title: '各具特色的民居', asterisk: true },
      { index: 9, title: '和田的维吾尔', asterisk: true },
      { index: 10, title: '十六年前的回忆' },
      { index: 11, title: '灯光', asterisk: true },
      { index: 12, title: '为人民服务' },
      { index: 13, title: '一夜的工作', asterisk: true },
      { index: 14, title: '卖火柴的小女孩' },
      { index: 15, title: '凡卡' },
      { index: 16, title: '《鲁滨孙漂流记》', asterisk: true },
      { index: 17, title: '《汤姆·索亚历险记》', asterisk: true },
      { index: 18, title: '跨越百年的美丽' },
      { index: 19, title: '千年梦圆在今朝', asterisk: true },
      { index: 20, title: '真理诞生于一百个问号之后' },
      { index: 21, title: '我最好的老师', asterisk: true },
    ],
  },
];

// renjiaoshe.forEach(book => {
//   if (book.articles.length !== book.articles[book.articles.length - 1].index) {
//     console.log(`Book "${book.bookName}" has incorrect article indices.`);
//   }
// });